config/routes.rb
ClinicaBovinos::Application.routes.draw do

  resources_path_names new: "novo", edit: "editar"

  with_options except: :show do |opt|
    opt.resources :bovinos
    opt.resources :fazendas
    opt.resources :inseminadores
    opt.resources :inseminacoes
    opt.resources :rebanhos, except: :show do
      resources :bovinos, only: [:index, :create, :destroy], controller: 'rebanhos/bovinos'
    end
  end

  namespace :relatorios do
    resources :inseminacoes_realizadas, only: [:index, :create]
  end

  root to: 'home#index'
end

app/models/rebanho.rb
class Rebanho < ActiveRecord::Base
  has_and_belongs_to_many :bovinos

  validates_presence_of :nome
end

app/controllers/rebanhos/bovinos_controller.rb
class Rebanhos::BovinosController < ApplicationController
  before_action :set_rebanho
  before_action :set_bovino, only: [:create, :destroy]
  before_action :set_menu

  def index
    @bovinos = Bovino.where.not(id: @rebanho.bovinos.pluck(:id))
  end

  def create
    @rebanho.bovinos << @bovino
    redirect_to :back, notice: 'Bovino adicionado no rebanho com sucesso.'
  end

  def destroy
    @rebanho.bovinos.delete(@bovino)
    redirect_to :back, notice: 'Bovino removido do rebanho com sucesso.'
  end

  private
    def set_rebanho
      @rebanho = Rebanho.find(params[:rebanho_id])
    end

    def set_bovino
      @bovino = Bovino.find(params[:id])
    end

    def set_menu
      @painel_ativo = :cadastros
      @menu_ativo   = :rebanhos
    end
end

app/controllers/rebanhos_controller.rb
class RebanhosController < ApplicationController
  before_action :set_rebanho, only: [:edit, :update, :destroy]
  before_action :set_menu

  # GET /rebanhos
  def index
    @rebanhos = Rebanho.all
  end

  # GET /rebanhos/new
  def new
    @rebanho = Rebanho.new
  end

  # GET /rebanhos/1/edit
  def edit
  end

  # POST /rebanhos
  def create
    @rebanho = Rebanho.new(rebanho_params)

    if @rebanho.save
      redirect_to edit_rebanho_path(@rebanho), notice: 'Rebanho criado com sucesso.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /rebanhos/1
  def update
    if @rebanho.update(rebanho_params)
      redirect_to rebanhos_path, notice: 'Rebanho atualizado com sucesso.'
    else
      render action: 'edit'
    end
  end

  # DELETE /rebanhos/1
  def destroy
    @rebanho.destroy
    redirect_to rebanhos_path, notice: 'Rebanho removido com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rebanho
      @rebanho = Rebanho.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rebanho_params
      params.require(:rebanho).permit(:nome)
    end

    def set_menu
      @painel_ativo = :cadastros
      @menu_ativo   = :rebanhos
    end
end

app/helpers/rebanhos_helper.rb
module RebanhosHelper
end

app/views/rebanhos/_bovinos.html.erb
<h3>
  Bovinos (<%= rebanho.bovinos.size %>)
  <%= link_to 'Adicionar', rebanho_bovinos_path(rebanho), class: 'btn btn-primary pull-right' %>
</h3>

<hr>

<% if rebanho.bovinos.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Número</th>
        <th>Nome</th>
        <th>Raça</th>
        <th>Pelagem</th>
        <th>Sexo</th>
        <th>Nascimento</th>
        <th class="col-xs-2"></th>
      </tr>
    </thead>

    <tbody>
      <% rebanho.bovinos.each do |bovino| %>
        <tr>
          <td><%= bovino.numero %></td>
          <td><%= bovino.nome %></td>
          <td><%= bovino.raca %></td>
          <td><%= bovino.pelagem %></td>
          <td><%= bovino.sexo %></td>
          <td><%= l bovino.data_nascimento %></td>
          <td>
            <%= link_to 'Remover', [rebanho, bovino], method: :delete, data: { confirm: 'Tem certeza?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info">
    <p>
      Nenhum bovino encontrado.
      <%= link_to 'Adicione um novo bovino a este rebanho.', rebanho_bovinos_path(rebanho), class: 'alert-link' %>
    </p>
  </div>
<% end %>

app/views/rebanhos/_form.html.erb
<%= form_for(@rebanho) do |f| %>
  <% if @rebanho.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@rebanho.errors.count, 'erro não permitiu', 'errors não permitiram') %> salvar a rebanho:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @rebanho.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, '* Nome' %>
    <%= f.text_field :nome, class: 'form-control' %>
  </div>

  <% if @rebanho.persisted? %>
    <%= render 'bovinos', rebanho: @rebanho %>
  <% end %>

  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancelar', rebanhos_path, class: 'btn btn-default' %>
<% end %>

app/views/rebanhos/edit.html.erb
<div class="page-header">
  <h1>
    Editar Rebanho
    <%= link_to 'Voltar', rebanhos_path, class: 'btn btn-default pull-right' %>
  </h1>
</div>

<%= render 'form' %>

app/views/rebanhos/index.html.erb
<div class="page-header">
  <h1>
    Lista de Rebanhos
    <%= link_to 'Novo Rebanho', new_rebanho_path, class: 'btn btn-primary pull-right' %>
  </h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Qtde Bovinos</th>
      <th class="col-xs-3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rebanhos.each do |rebanho| %>
      <tr>
        <td><%= rebanho.nome %></td>
        <td><%= rebanho.bovinos.size %></td>
        <td>
          <%= link_to 'Editar', edit_rebanho_path(rebanho) %> |
          <%= link_to 'Remover', rebanho, method: :delete, data: { confirm: 'Tem certeza?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rebanhos/new.html.erb
<div class="page-header">
  <h1>
    Novo Rebanho
    <%= link_to 'Voltar', rebanhos_path, class: 'btn btn-default pull-right' %>
  </h1>
</div>

<%= render 'form' %>