config/routes.rb
ClinicaBovinos::Application.routes.draw do

  resources_path_names new: "novo", edit: "editar"

  with_options except: :show do |opt|
    opt.resources :bovinos
    opt.resources :fazendas
    opt.resources :inseminadores
    opt.resources :inseminacoes
    opt.resources :rebanhos, except: :show do
      resources :bovinos, only: [:index, :create, :destroy], controller: 'rebanhos/bovinos'
    end
  end

  namespace :relatorios do
    resources :inseminacoes_realizadas, only: [:index, :create]
  end

  root to: 'home#index'
end

app/models/bovino.rb
class Bovino < ActiveRecord::Base
  PELAGENS = [
    'Nelore'
  ]

  RACAS = [
    'Aberdeen Angus',
    'Blanc-Blue-Belge',
    'Blonded`Aquitaine',
    'Belgian Blue',
    'Bradford',
    'Brahman',
    'Brangus',
    'Bravon',
    'Charolesa',
    'Canchim',
    'Charolês',
    'Chianina',
    'Caracu',
    'Carabao ou Rosilho',
    'Devon',
    'Gir',
    'Guzerá',
    'Hereford',
    'InduBrasil',
    'Limousin',
    'Marchigiana',
    'Nelore',
    'Piomontesa',
    'Red Angus',
    'Romagnolo',
    'Santa Gertrudis',
    'Simental',
    'Shorthorn',
    'Tabapuã'
  ]

  SEXOS = %w(Macho Fêmea).each do |sexo|
    scope sexo.parameterize, -> { where sexo: sexo }
  end

  belongs_to :fazenda
  has_many :inseminacoes, dependent: :restrict_with_exception

  validates_presence_of :fazenda_id, :numero, :nome, :pelagem, :raca, :sexo, :data_nascimento
  validates_inclusion_of :pelagem, in: PELAGENS, allow_blank: true
  validates_inclusion_of :raca, in: RACAS, allow_blank: true
  validates_inclusion_of :sexo, in: SEXOS, allow_blank: true
end

app/controllers/bovinos_controller.rb
class BovinosController < ApplicationController
  before_action :set_bovino, only: [:edit, :update, :destroy]
  before_action :set_menu

  # GET /bovinos
  def index
    @bovinos = Bovino.all
  end

  # GET /bovinos/new
  def new
    @bovino = Bovino.new
  end

  # GET /bovinos/1/edit
  def edit
  end

  # POST /bovinos
  def create
    @bovino = Bovino.new(bovino_params)

    if @bovino.save
      redirect_to bovinos_path, notice: 'Bovino criado com sucesso.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /bovinos/1
  def update
    if @bovino.update(bovino_params)
      redirect_to bovinos_path, notice: 'Bovino atualizado com sucesso.'
    else
      render action: 'edit'
    end
  end

  # DELETE /bovinos/1
  def destroy
    @bovino.destroy
    redirect_to bovinos_path, notice: 'Bovino removido com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bovino
      @bovino = Bovino.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def bovino_params
      params.require(:bovino).permit(
        :fazenda_id, :numero, :nome, :pai, :mae, :raca, :pelagem, :sexo, :data_nascimento)
    end

    def set_menu
      @painel_ativo = :cadastros
      @menu_ativo   = :bovinos
    end
end

app/controllers/rebanhos/bovinos_controller.rb
class Rebanhos::BovinosController < ApplicationController
  before_action :set_rebanho
  before_action :set_bovino, only: [:create, :destroy]
  before_action :set_menu

  def index
    @bovinos = Bovino.where.not(id: @rebanho.bovinos.pluck(:id))
  end

  def create
    @rebanho.bovinos << @bovino
    redirect_to :back, notice: 'Bovino adicionado no rebanho com sucesso.'
  end

  def destroy
    @rebanho.bovinos.delete(@bovino)
    redirect_to :back, notice: 'Bovino removido do rebanho com sucesso.'
  end

  private
    def set_rebanho
      @rebanho = Rebanho.find(params[:rebanho_id])
    end

    def set_bovino
      @bovino = Bovino.find(params[:id])
    end

    def set_menu
      @painel_ativo = :cadastros
      @menu_ativo   = :rebanhos
    end
end

app/helpers/bovinos_helper.rb
module BovinosHelper
end

app/views/bovinos/_form.html.erb
<%= form_for(@bovino) do |f| %>
  <% if @bovino.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@bovino.errors.count, 'erro não permitiu', 'errors não permitiram') %> salvar o bovino:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @bovino.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fazenda_id, '* Fazenda' %>
    <%= f.collection_select :fazenda_id, Fazenda.order(:nome), :id, :nome, { prompt: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :numero, '* Número' %>
    <%= f.text_field :numero, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :nome, '* Nome' %>
    <%= f.text_field :nome, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pai %>
    <%= f.text_field :pai, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :mae %>
    <%= f.text_field :mae, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :raca, '* Raça' %>
    <%= f.select :raca, Bovino::RACAS, { prompt: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pelagem, '* Pelagem' %>
    <%= f.select :pelagem, Bovino::PELAGENS, { prompt: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong>* Sexo:</strong>
    <% Bovino::SEXOS.each do |sexo| %>
      <label class="radio-inline">
        <%= f.radio_button :sexo, sexo %> <%= sexo %>
      </label>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :data_nascimento, '* Data de Nascimento' %>
    <%= f.date_field :data_nascimento, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancelar', bovinos_path, class: 'btn btn-default' %>
<% end %>

app/views/bovinos/edit.html.erb
<div class="page-header">
  <h1>
    Editar Bovino
    <%= link_to 'Voltar', bovinos_path, class: 'btn btn-default pull-right' %>
  </h1>
</div>

<%= render 'form' %>

app/views/bovinos/index.html.erb
<div class="page-header">
  <h1>
    Lista de Bovinos
    <%= link_to 'Novo Bovino', new_bovino_path, class: 'btn btn-primary pull-right' %>
  </h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Número</th>
      <th>Nome</th>
      <th>Raça</th>
      <th>Pelagem</th>
      <th>Sexo</th>
      <th>Nascimento</th>
      <th class="col-xs-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @bovinos.each do |bovino| %>
      <tr>
        <td><%= bovino.numero %></td>
        <td><%= bovino.nome %></td>
        <td><%= bovino.raca %></td>
        <td><%= bovino.pelagem %></td>
        <td><%= bovino.sexo %></td>
        <td><%= l bovino.data_nascimento %></td>
        <td>
          <%= link_to 'Editar', edit_bovino_path(bovino) %> |
          <%= link_to 'Remover', bovino, method: :delete, data: { confirm: 'Tem certeza?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bovinos/new.html.erb
<div class="page-header">
  <h1>
    Novo Bovino
    <%= link_to 'Voltar', bovinos_path, class: 'btn btn-default pull-right' %>
  </h1>
</div>

<%= render 'form' %>