config/routes.rb
ClinicaBovinos::Application.routes.draw do

  resources_path_names new: "novo", edit: "editar"

  with_options except: :show do |opt|
    opt.resources :bovinos
    opt.resources :fazendas
    opt.resources :inseminadores
    opt.resources :inseminacoes
    opt.resources :rebanhos, except: :show do
      resources :bovinos, only: [:index, :create, :destroy], controller: 'rebanhos/bovinos'
    end
  end

  namespace :relatorios do
    resources :inseminacoes_realizadas, only: [:index, :create]
  end

  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Clínica de Bovinos</title>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Alterar navegação</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Clínica de Bovinos', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown<%= ' active' if @painel_ativo == :cadastros %>">
              <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Cadastros <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                <%= content_tag :li, role: 'presentation', class: ('active' if @menu_ativo == :fazendas) do %>
                  <%= link_to 'Fazendas', fazendas_path, tabindex: '-1', role: 'menuitem' %>
                <% end %>
                <%= content_tag :li, role: 'presentation', class: ('active' if @menu_ativo == :bovinos) do %>
                  <%= link_to 'Bovinos', bovinos_path, tabindex: '-1', role: 'menuitem' %>
                <% end %>
                <%= content_tag :li, role: 'presentation', class: ('active' if @menu_ativo == :rebanhos) do %>
                  <%= link_to 'Rebanhos', rebanhos_path, tabindex: '-1', role: 'menuitem' %>
                <% end %>
                <%= content_tag :li, role: 'presentation', class: ('active' if @menu_ativo == :inseminadores) do %>
                  <%= link_to 'Inseminadores', inseminadores_path, tabindex: '-1', role: 'menuitem' %>
                <% end %>
                <%= content_tag :li, role: 'presentation', class: ('active' if @menu_ativo == :inseminacoes) do %>
                  <%= link_to 'Inseminações', inseminacoes_path, tabindex: '-1', role: 'menuitem' %>
                <% end %>
              </ul>
            </li>
            <li class="dropdown<%= 'active' if @painel_ativo == :relatorios %>">
              <a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown">Relatórios <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
                <%= content_tag :li, role: 'presentation', class: ('active' if @menu_ativo == :inseminacoes_realizadas) do %>
                  <%= link_to 'Inseminações Realizadas', relatorios_inseminacoes_realizadas_path, tabindex: '-1', role: 'menuitem' %>
                <% end %>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-6 col-sm-3 sidebar hidden-print hidden-xs" role="navigation">
          <div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                    Cadastros
                  </a>
                </h4>
              </div>
              <div id="collapseOne" class="panel-collapse collapse<%= ' in' if @painel_ativo == :cadastros %>">
                <div class="panel-body">
                  <div class="list-group">
                    <%= link_to 'Fazendas', fazendas_path, class: ['list-group-item', ('active' if @menu_ativo == :fazendas)] %>
                    <%= link_to 'Bovinos', bovinos_path, class: ['list-group-item', ('active' if @menu_ativo == :bovinos)] %>
                    <%= link_to 'Rebanhos', rebanhos_path, class: ['list-group-item', ('active' if @menu_ativo == :rebanhos)] %>
                    <%= link_to 'Inseminadores', inseminadores_path, class: ['list-group-item', ('active' if @menu_ativo == :inseminadores)] %>
                    <%= link_to 'Inseminações', inseminacoes_path, class: ['list-group-item', ('active' if @menu_ativo == :inseminacoes)] %>
                  </div>
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                    Relatórios
                  </a>
                </h4>
              </div>
              <div id="collapseTwo" class="panel-collapse collapse<%= ' in' if @painel_ativo == :relatorios %>">
                <div class="panel-body">
                  <div class="list-group">
                    <%= link_to 'Inseminações Realizadas', relatorios_inseminacoes_realizadas_path, class: ['list-group-item', ('active' if @menu_ativo == :inseminacoes_realizadas)] %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div><!--/span-->

        <div class="col-xs-12 col-sm-9 main">
          <% if notice %>
            <div class="alert alert-success alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= notice %>
            </div>
          <% end %>
          <% if alert %>
            <div class="alert alert-warning alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= alert %>
            </div>
          <% end %>

          <%= yield %>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Clínica de Bovinos 2013</p>
      </footer>

    </div><!-- /.container -->

    <%= javascript_include_tag "application" %>
  </body>
</html>